package:
  name: pydp
  version: "0.2.3"

source:
  hg_url: https://bitbucket.org/aroth85/pydp
  hg_tag: 0.2.3

requirements:
  build:
    - python

  run:
    - scipy

about:
  home: https://bitbucket.org/aroth85/pydp
